import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Main } from '../components/Main';
import { Header } from '../components/Header';
import { Title } from '../components/Title';

const inter = Inter({ subsets: ['latin'] });

export default function About() {
  return (
    <div>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Title title="about" />

      <Main page="about" />
    </div>
  );
}
